service: virgin-media-postcode-checker

provider:
  name: aws
  runtime: nodejs8.10
  stage: prod
  region: eu-west-1
  memorySize: 2048
  timeout: 60
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "ses:SendEmail"
      Resource: "*"

functions:
  check:
    handler: handler.check
    events:
      - schedule: cron(0 12 * * ? *)
